version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: bb-postgres
    environment:
      POSTGRES_DB: bbframework
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # Пробрасываем порт на хост
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: